modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="gribtweaks" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies."gribtweaks"]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies."gribtweaks"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."gribtweaks"]]
   modId="ftbic"
   mandatory=true
   versionRange="1900.1.7-build.221"
   ordering="NONE"
   side="BOTH"

[[dependencies."gribtweaks"]]
   modId="ftblibrary"
   mandatory=true
   versionRange="1902.4.1-build.236"
   ordering="NONE"
   side="BOTH"